#!/usr/bin/env python
"""Generate pyfimer's REST point table from the VSN-SunSpec point mapping.

Reads ``docs/vsn-sunspec-point-mapping.json`` (the mapping curated in the
ha-abb-fimer-pvi-vsn-rest project) and writes
``custom_components/fimer/pyfimer/rest/_mapping_data.py``: one row per point
with its VSN300 and VSN700 REST names, its vocabulary name, native unit and
kind, plus the Home Assistant presentation metadata the integration uses.

Run it after updating the mapping::

    python scripts/generate_rest_mapping.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAPPING = ROOT / "docs" / "vsn-sunspec-point-mapping.json"
OUTPUT = ROOT / "custom_components" / "fimer" / "pyfimer" / "rest" / "_mapping_data.py"
TRANSLATIONS = ROOT / "custom_components" / "fimer" / "translations" / "en.json"
ICONS = ROOT / "custom_components" / "fimer" / "icons.json"

# Points whose value is a code from an Aurora state table.
STATE_POINTS = {
    "GlobalSt",
    "InverterSt",
    "DcSt1",
    "DcSt2",
    "DcSt3",
    "AlarmSt",
    "AlarmState",
    "GlobState",
    "InvState",
    "DC1State",
    "DC2State",
    "DC3State",
    "wlan0_mode",
    "BattExtCtrlState",
    "BattMode",
    "BatteryMode",
}


def kind_of(row: dict, name: str) -> str:
    state_class = row["HA State Class"]
    if name in STATE_POINTS:
        return "state"
    if state_class == "measurement":
        return "measurement"
    if state_class in ("total", "total_increasing"):
        return "total"
    return "info"


def native_unit(row: dict) -> str | None:
    unit = row["HA Unit of Measurement"] or None
    # the VSN sends watt-hours; the mapping's kWh is a display choice
    if row["HA Device Class"] == "energy" and unit == "kWh":
        return "Wh"
    if unit == "MOhm":
        return "MΩ"
    return unit


def main() -> None:
    rows = json.loads(MAPPING.read_text(encoding="utf-8"))
    lines = [
        '"""REST point table, generated by scripts/generate_rest_mapping.py. Do not edit."""',
        "",
        "# fmt: off",
        "# ruff: noqa: E501",
        "",
        "REST_POINT_ROWS: tuple[tuple[str, str | None, str | None, str | None, str, str, str, str, str | None, str | None, str | None, int | None, str | None, str | None, str | None, str], ...] = (",
        "    # (name, vsn300, vsn700, unit, kind, category, models, display_name,",
        "    #  device_class, state_class, entity_category, precision, icon, scope, accumulation, ha_name)",
    ]
    seen: dict[str, str] = {}
    for row in rows:
        name = row["SunSpec Normalized Name"]
        vsn300 = None if row["REST Name (VSN300)"] in ("N/A", "") else row["REST Name (VSN300)"]
        vsn700 = None if row["REST Name (VSN700)"] in ("N/A", "") else row["REST Name (VSN700)"]
        if name in seen:
            raise SystemExit(f"duplicate point name {name!r} ({seen[name]} and {row['HA Name']})")
        seen[name] = row["HA Name"]
        precision = row["Suggested Display Precision"]
        values = (
            name,
            vsn300,
            vsn700,
            native_unit(row),
            kind_of(row, name),
            row["Category"],
            ",".join(row["models"]),
            row["HA Display Name"],
            row["HA Device Class"] or None,
            row["HA State Class"] or None,
            row["Entity Category"] or None,
            int(precision) if precision not in ("", None) else None,
            row["HA Icon"] or None,
            row["Sensor Scope"] or None,
            row["Accumulation Mode"] or None,
            row["HA Name"],
        )
        lines.append(f"    {values!r},")
    lines += [")", "", "# fmt: on", ""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(rows)} rows to {OUTPUT.relative_to(ROOT)}")  # noqa: T201
    _merge_presentation(rows)


def _merge_presentation(rows: list[dict]) -> None:
    """Add entity names and icons for REST points; hand-written keys win."""
    translations = json.loads(TRANSLATIONS.read_text(encoding="utf-8"))
    sensors = translations["entity"].setdefault("sensor", {})
    icons = json.loads(ICONS.read_text(encoding="utf-8"))
    icon_sensors = icons["entity"].setdefault("sensor", {})
    added = 0
    for row in rows:
        key = row["HA Name"]
        if key not in sensors:
            sensors[key] = {"name": row["HA Display Name"]}
            added += 1
        if row["HA Icon"] and key not in icon_sensors:
            icon_sensors[key] = {"default": row["HA Icon"]}
    TRANSLATIONS.write_text(json.dumps(translations, indent=2, ensure_ascii=False) + "\n")
    ICONS.write_text(json.dumps(icons, indent=2, ensure_ascii=False) + "\n")
    print(f"added {added} entity names to {TRANSLATIONS.relative_to(ROOT)}")  # noqa: T201


if __name__ == "__main__":
    main()
